//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistAcademia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Peso { get; set; }
        public string Altura { get; set; }
        public string Idade { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string Objetivo { get; set; }
        public bool Ativo { get; set; }
        public int AcademiaId { get; set; }
    
        public virtual Academia Academia { get; set; }
    }
}
